#knnf_user:
#    resource: "@KnnfUserBundle/Resources/config/routing.yml"
#    prefix:   /
home:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:Index:index" }

knnf_whatsup:
    resource: "@KnnfWhatsupBundle/Resources/config/routing.yml"
    prefix:   /whatsup

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /whatsup/
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /whatsup/profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /whatsup/register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /whatsup/resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /whatsup/profile
