#security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
security:
    encoders:
<<<<<<< HEAD
        Knnf\UserBundle\Entity\User: sha512
=======
        Symfony\Component\Security\Core\User\User: plaintext
        Knnf\WhatsupBundle\Entity\User: sha512
>>>>>>> 6bbee3121ecdb5daf3b2cae37f9561fa75aadaf5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
<<<<<<< HEAD
        # … le pare-feu « dev »
        # Firewall principal pour le reste de notre site
=======
>>>>>>> 6bbee3121ecdb5daf3b2cae37f9561fa75aadaf5
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
<<<<<<< HEAD
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     /whatsup/index/index
=======
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /whatsup
>>>>>>> 6bbee3121ecdb5daf3b2cae37f9561fa75aadaf5
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/whatsup/admin/index/, role: ROLE_ADMIN }
