index:
    pattern: /index/index/
    defaults: { _controller: "KnnfWhatsupBundle:Index:index" }

index_todo:
    pattern: /index/todo
    defaults: { _controller: "KnnfWhatsupBundle:Index:todo" }

admin:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/admin.yml"
  prefix: /admin

user:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/user.yml"
  prefix: /user

article:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/article.yml"
  prefix: /article

category:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/category.yml"
  prefix: /category

event:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/event.yml"
  prefix: /event

media:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/media.yml"
  prefix: /media

stat:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/stat.yml"
  prefix: /stat

annotation:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/annotation.yml"
  prefix: /annotation

organigramme:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/organigramme.yml"
  prefix: /organigramme

profile:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/profile.yml"
  prefix: /profile

lookbook:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/lookbook.yml"
  prefix: /lookbook

setting:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/setting.yml"
  prefix: /setting




registration:
    pattern:  /registration/register
    defaults: { _controller: "KnnfWhatsupBundle:Registration:register" }

registration_confirmed:
    pattern:  /registration/confirmed
    defaults: { _controller: "KnnfWhatsupBundle:Registration:confirmed" }

registration_confirm:
    pattern:  /registration/confirm/{token}
    defaults: { _controller: "KnnfWhatsupBundle:Registration:confirm" }

registration_checkmail:
    pattern:  /registration/checkEmail
    defaults: { _controller: "KnnfWhatsupBundle:Registration:checkEmail" }


contact_index:
    pattern: /contact
    defaults: { _controller: KnnfWhatsupBundle:Contact:index }


