knnf_whatsup_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: KnnfWhatsupBundle:Default:index }

#INDEX
index:
    pattern: /index/index/
    defaults: { _controller: KnnfWhatsupBundle:Index:index }

user_index:
    pattern: /user/index/
    defaults: { _controller: KnnfWhatsupBundle:User:index }

user_add:
    pattern: /user/add/
    defaults: { _controller: KnnfWhatsupBundle:User:add }

user_delete:
    pattern: /user/delete/
    defaults: { _controller: KnnfWhatsupBundle:User:delete }

#ARTICLE
article_index:
    pattern: /article/index/
    defaults: { _controller: KnnfWhatsupBundle:Article:index }

article_add:
    pattern: /article/add/
    defaults: { _controller: KnnfWhatsupBundle:Article:add }

article_edit:
    pattern: /article/edit/
    defaults: { _controller: KnnfWhatsupBundle:Article:edit }

article_delete:
    pattern: /article/delete/
    defaults: { _controller: KnnfWhatsupBundle:Article:delete }

article_activate:
    pattern: /article/activate/
    defaults: { _controller: KnnfWhatsupBundle:Article:activate }

#CATEGORY
category_index:
    pattern: /category/index/
    defaults: { _controller: KnnfWhatsupBundle:Category:index }

category_add:
    pattern: /category/add/
    defaults: { _controller: KnnfWhatsupBundle:Category:add }

category_edit:
    pattern: /category/edit/
    defaults: { _controller: KnnfWhatsupBundle:Category:edit }

category_delete:
    pattern: /category/delete/
    defaults: { _controller: KnnfWhatsupBundle:Category:delete }

category_activate:
    pattern: /category/activate/
    defaults: { _controller: KnnfWhatsupBundle:Category:activate }

#EVENT
event_index:
    pattern: /event/index
    defaults: { _controller: KnnfWhatsupBundle:Event:index }

event_add:
    pattern: /event/add/
    defaults: { _controller: KnnfWhatsupBundle:Event:add }

event_edit:
    pattern: /event/edit/
    defaults: { _controller: KnnfWhatsupBundle:Event:edit }

event_delete:
    pattern: /event/delete/
    defaults: { _controller: KnnfWhatsupBundle:Event:delete }

event_activate:
    pattern: /event/activate/
    defaults: { _controller: KnnfWhatsupBundle:Event:activate }

#MEDIA
media:
    pattern: /media/index/
    defaults: { _controller: KnnfWhatsupBundle:Media:index }

media_show:
    pattern: /media/show/{id}
    defaults: { _controller: KnnfWhatsupBundle:Media:show }

media_edit:
    pattern: /media/edit/{id}
    defaults: { _controller: KnnfWhatsupBundle:Media:edit }

media_update:
    pattern: /media/update/{id}
    defaults: { _controller: KnnfWhatsupBundle:Media:update }

media_delete:
    pattern: /media/delete/{id}
    defaults: { _controller: KnnfWhatsupBundle:Media:delete }

media_new:
    pattern: /media/new/
    defaults: { _controller: KnnfWhatsupBundle:Media:new }

media_create:
    pattern: /media/create/
    defaults: { _controller: KnnfWhatsupBundle:Media:create }