index:
    pattern: /index/index/
    defaults: { _controller: "KnnfWhatsupBundle:Index:index" }

admin:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/admin.yml"
  prefix: /admin

user:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/user.yml"
  prefix: /user

article:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/article.yml"
  prefix: /article

category:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/category.yml"
  prefix: /category

event:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/event.yml"
  prefix: /event

media:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/media.yml"
  prefix: /media

stat:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/stat.yml"
  prefix: /stat

annotation:
  resource: "@KnnfWhatsupBundle/Resources/config/routing/annotation.yml"
  prefix: /annotation

registration:
    pattern:  /registration/register
    defaults: { _controller: "KnnfWhatsupBundle:Registration:register" }