parameters:
#    knnf_whatsup.example.class: Knnf\WhatsupBundle\Example

services:
    knnf_user.registration.form.type:
        class: Knnf\WhatsupBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: knnf_user_registration }