<?php

namespace Knnf\WhatsupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * AnnotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnotationRepository extends EntityRepository
{
	public function getMaxVote($category = null)
    {
    	if($category != null)
    	{
	        $q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.category = '.$category->getId())
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->groupBy('annotation.idarticle')
	            ->setParameter('AnnotationType', 'like');
	            ;
	        $query = $q->getQuery();
        }
        else
        {
        	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->groupBy('annotation.idArticle')
	            ->setParameter('AnnotationType', 'like');


	        $query = $q->getQuery();

        }
 	

        $query->getResult(); 
 
        return $q;
    }

    public function getBestArticleOfTheMonth($category = null)
    {
    	$now =  '2014-06-01 00:00:00';
    	$now2 = '2014-06-28 00:00:00';
    	$q = $this->_em->createQueryBuilder()
	            ->select('annotation.idArticle,count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.dateinsert > (:dateinsert)')
	            ->andWhere('annotation.dateinsert < (:dateinsert2)')
	            ->setParameter('AnnotationType', 'like')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2);
	     
	     return $q->getQuery()->getResult();
    }

    public function getBestUserOfTheMonth($category = null)
    {
    	$now =  '2014-06-01 00:00:00';
    	$now2 = '2014-06-28 00:00:00';
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idUser) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.dateinsert > (:dateinsert)')
	            ->andWhere('annotation.dateinsert < (:dateinsert2)')
	            ->setParameter('AnnotationType', 'like')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2);
	     
	     return $q->getQuery()->getResult();
    }

     public function getBestUserOfTheMonth3($category = null)
    {
    	$now =  '2014-06-01 00:00:00';
    	$now2 = '2014-06-28 00:00:00';
    	$q = $this->_em->createQueryBuilder()
	            ->select('annotation.idUser')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.dateinsert > (:dateinsert)')
	            ->andWhere('annotation.dateinsert < (:dateinsert2)')
	            ->groupBy('annotation.idUser')
	            ->setParameter('AnnotationType', 'like')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2);
	     
	     return $q->getQuery()->getResult();
    }

       public function getBestUserOfTheMonth2($id = null)
    {
    	$now =  '2014-06-01 00:00:00';
    	$now2 = '2014-06-28 00:00:00';
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idUser) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.idUser = (:user)')
	            ->setParameter('AnnotationType', 'like')
	            ->setParameter('user', $id);
	     
	     return $q->getQuery()->getResult();
    }

    public function getDailyComment()
    {
    	$now = date('Y-m-d 00:00:00');
    	$now2 = date('Y-m-d 23:59:59');
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.dateinsert > (:dateinsert)')
	            ->andWhere('annotation.dateinsert < (:dateinsert2)')
	            ->setParameter('AnnotationType', 'comments')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2);
	     
	     return $q->getQuery()->getResult();

    }

	public function getComment($id=null)
    {
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.idUser = (:user)')
	            ->setParameter('AnnotationType', 'comments')
	            ->setParameter('user', $id);
	     
	     return $q->getQuery()->getResult();

    }

    public function getDailySignalement()
    {
    	$now = date('Y-m-d 00:00:00');
    	$now2 = date('Y-m-d 23:59:59');
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.dateinsert > (:dateinsert)')
	            ->andWhere('annotation.dateinsert < (:dateinsert2)')
	            ->setParameter('AnnotationType', 'signalement')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2);
	     
	     return $q->getQuery()->getResult();

    }


    public function getVoteByArticle(){
    	$q = $this->_em->createQueryBuilder()
	            ->select('article.title,article.path,article.slug,annotation.idArticle as id,count(annotation.idArticle) as total')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->from('KnnfWhatsupBundle:Article','article')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->andWhere('annotation.idArticle = article.id')
	            ->setParameter('AnnotationType', 'like')
	            ->groupBy('annotation.idArticle')
	            ->orderBy('total','desc')
	    ;
	     
	     return $q->getQuery()->getResult();

    }


	
}
