<?php

namespace Knnf\WhatsupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnnotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnotationRepository extends EntityRepository
{
	public function getMaxVote($category = null)
    {
    	if($category != null)
    	{
	        $q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.category = '.$category->getId())
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->groupBy('annotation.idarticle')
	            ->setParameter('AnnotationType', 'like');
	            ;
	        $query = $q->getQuery();
        }
        else
        {
        	$q = $this->_em->createQueryBuilder()
	            ->select('count(annotation.idArticle) as nombre')
	            ->from('KnnfWhatsupBundle:Annotation','annotation')
	            ->where('annotation.AnnotationType = (:AnnotationType)')
	            ->groupBy('annotation.idArticle')
	            ->setParameter('AnnotationType', 'like');


	        $query = $q->getQuery();

        }
 
        $query->getResult(); 
 
        return $q;
    }
}
