<?php

namespace Knnf\WhatsupBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Knnf\WhatsupBundle\Entity\Article;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

	
	public function delete($id){
			if(!$id) die('Missing parameter');

			$em = $this->getEntityManager();
            $article = $em->getRepository('KnnfWhatsupBundle:Article')->find($id);
            $em->remove($article);
            $em->flush();
	}

	public function save(array $data){

		$em = $this->getEntityManager();

		$article = new Article();

		if($data['id']){
			$article->setId($data['id']);
			$article->setDateupdate(date());
		} 
		if($data['title']) $article->setTitle($data['title']);
		if($data['slug']) $article->setSlug($data['slug']);
		if($data['content']) $article->setContent($data['content']);
		if($data['picture']) $article->setPicture($data['picture']);
		if($data['status']) $article->setStatus($data['status']);
		if($data['activate']) $article->setActivate($data['activate']);
		

		$category = $em->getRepository('KnnfWhatsupBundle:Category')->findBy(array('id' => $data['categoryid']));
		$article->setCategory($category);

		$user = $em->getRepository('KnnfWhatsupBundle:User')->findBy(array('id' => $data['userid']));
		$article->setUser($user);
		
	}

	public function getList($page=1, $maxperpage=10, $category = null)
    {
    	if($category != null)
    	{
	        $q = $this->_em->createQueryBuilder()
	            ->select('article')
	            ->from('KnnfWhatsupBundle:Article','article')
	            ->where('article.category = '.$category->getId());
        }
        else
        {
        	$q = $this->_em->createQueryBuilder()
	            ->select('article')
	            ->from('KnnfWhatsupBundle:Article','article');
        }
 
        $q->setFirstResult(($page-1) * $maxperpage)
            ->setMaxResults($maxperpage);
 
        return new Paginator($q);
    }

    public function getDailyArticle()
    {
    	$now = date('Y-m-d 00:00:00');
    	$now2 = date('Y-m-d 23:59:59');
    	$q = $this->_em->createQueryBuilder()
	            ->select('count(Article.id) as nombre')
	            ->from('KnnfWhatsupBundle:Article','Article')
	            ->Where('Article.dateinsert > (:dateinsert)')
	            ->andWhere('Article.dateinsert < (:dateinsert2)')
	            ->andWhere('Article.activate = (:activate)')
	            ->setParameter('dateinsert', $now)
	            ->setParameter('dateinsert2', $now2)
	            ->setParameter('activate', 1);
	     
	            
	     return $q->getQuery()->getResult();
    }

    public function getCategoryView()
    {
    	$now = date('Y-m-d 00:00:00');
    	$now2 = date('Y-m-d 23:59:59');
    	$q = $this->_em->createQueryBuilder()
	            ->select(array('IDENTITY(Article.category) as categoryid','sum(Article.views) as views'))
	            ->from('KnnfWhatsupBundle:Article','Article')
	            ->groupBy('Article.category')
	            ->orderBy('views','desc')
	           ;
	     return $q->getQuery()->getResult();
    }


    public function changeArticleUser($id){
    	$qb = $this->em->createQueryBuilder();
		$q = $qb->update('KnnfWhatsupBundle:Article','Article')
		        ->set('Article.userid', '2')
		        ->where('Article.userid = ?1')
		        ->setParameter(1, $id)
		        ->getQuery();
		$p = $q->execute();
    }


   


}
