<?php

namespace Knnf\WhatsupBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
	public function fetchPairs(){
		$em = $this->getEntityManager();
		$categories = $em->getRepository('KnnfWhatsupBundle:Role')->findAll();

		foreach ($categories as $category) {
			$data[$category->getId()] = $category->getName();
		}

		return $data;
	}

	public function delete($id){
		if(!$id) die('Missing parameter');

		$em = $this->getEntityManager();
        $article = $em->getRepository('KnnfWhatsupBundle:Role')->find($id);
        $em->remove($article);
        $em->flush();
	}
}
