article:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:Article:index" }

article_show:
    pattern:  /{id}/show
    defaults: { _controller: "KnnfWhatsupBundle:Article:show" }

article_new:
    pattern:  /new
    defaults: { _controller: "KnnfWhatsupBundle:Article:new" }

article_create:
    pattern:  /article/create/{id}
    defaults: { _controller: "KnnfWhatsupBundle:Article:create" }
    requirements: { _method: post }

article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KnnfWhatsupBundle:Article:edit" }

article_update:
    pattern:  /{id}/update
    defaults: { _controller: "KnnfWhatsupBundle:Article:update" }
    requirements: { _method: post|put }

article_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "KnnfWhatsupBundle:Article:delete" }
    requirements: { _method: post|delete }
