article_home:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:Article:index" }

article:
    pattern:  /index/
    defaults: { _controller: "KnnfWhatsupBundle:Article:index" }

article_show:
    pattern:  /{slug}
    defaults: { _controller: "KnnfWhatsupBundle:Article:show" }

article_new:
    pattern:  /new
    defaults: { _controller: "KnnfWhatsupBundle:Article:new" }

article_add:
    pattern:  /add/
    defaults: { _controller: "KnnfWhatsupBundle:Article:add" }
    #requirements: { _method: post|put }

article_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KnnfWhatsupBundle:Article:edit" }

article_update:
    pattern:  /{id}/update
    defaults: { _controller: "KnnfWhatsupBundle:Article:update" }
    #requirements: { _method: post|put }

article_delete:
    pattern:  /delete/
    defaults: { _controller: "KnnfWhatsupBundle:Article:delete" }
   # requirements: { _method: post|delete }
    
article_activate:
    pattern:  /activate/
    defaults: { _controller: "KnnfWhatsupBundle:Article:activate" }
   # requirements: { _method: post|delete }
