category_home:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:Category:index" }

category:
    pattern:  /index/
    defaults: { _controller: "KnnfWhatsupBundle:Category:index" }

category_show:
    pattern:  /{id}/show
    defaults: { _controller: "KnnfWhatsupBundle:Category:show" }

category_new:
    pattern:  /new
    defaults: { _controller: "KnnfWhatsupBundle:Category:new" }

category_add:
    pattern:  /add
    defaults: { _controller: "KnnfWhatsupBundle:Category:add" }
    #requirements: { _method: post }

category_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KnnfWhatsupBundle:Category:edit" }

category_update:
    pattern:  /{id}/update
    defaults: { _controller: "KnnfWhatsupBundle:Category:update" }
    requirements: { _method: post|put }

category_delete:
    pattern:  /delete/
    defaults: { _controller: "KnnfWhatsupBundle:Category:delete" }
    requirements: { _method: post|delete }

category_activate:
    pattern:  /activate/
    defaults: { _controller: "KnnfWhatsupBundle:Category:activate" }
    requirements: { _method: post|delete }