event_home:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:Event:index" }

event_index:
    pattern:  /index
    defaults: { _controller: "KnnfWhatsupBundle:Event:index" }

event:
    pattern:  /event/index/
    defaults: { _controller: "KnnfWhatsupBundle:Event:index" }

event_show:
    pattern:  /{id}/show
    defaults: { _controller: "KnnfWhatsupBundle:Event:show" }

event_new:
    pattern:  /new
    defaults: { _controller: "KnnfWhatsupBundle:Event:new" }

event_add:
    pattern:  /add
    defaults: { _controller: "KnnfWhatsupBundle:Event:add" }
    #requirements: { _method: post }

event_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KnnfWhatsupBundle:Event:edit" }

event_update:
    pattern:  /{id}/update
    defaults: { _controller: "KnnfWhatsupBundle:Event:update" }
    requirements: { _method: post|put }

event_delete:
    pattern:  /delete/
    defaults: { _controller: "KnnfWhatsupBundle:Event:delete" }
    requirements: { _method: post|delete }

event_activate:
    pattern:  /activate/
    defaults: { _controller: "KnnfWhatsupBundle:Event:activate" }
    requirements: { _method: post|delete }