user_home:
    pattern:  /
    defaults: { _controller: "KnnfWhatsupBundle:User:index" }

user:
    pattern:  /index/
    defaults: { _controller: "KnnfWhatsupBundle:User:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "KnnfWhatsupBundle:User:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "KnnfWhatsupBundle:User:new" }

user_add:
    pattern:  /add
    defaults: { _controller: "KnnfWhatsupBundle:User:add" }
    #requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "KnnfWhatsupBundle:User:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "KnnfWhatsupBundle:User:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /delete/
    defaults: { _controller: "KnnfWhatsupBundle:User:delete" }
    requirements: { _method: post|delete }

user_activate:
    pattern:  /activate/
    defaults: { _controller: "KnnfWhatsupBundle:User:activate" }
    requirements: { _method: post|delete }

user_login:
    pattern:  /login/
    defaults: { _controller: "KnnfWhatsupBundle:User:login" }
    #requirements: { _method: post|delete }