parameters:
#    knnf_user.example.class: Knnf\UserBundle\Example

services:
#    knnf_user.example:
#        class: %knnf_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
